{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.hosts -}}

{{- if $.Capabilities.APIVersions.Has "extensions/v1beta1/Ingress" -}}
apiVersion: extensions/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  {{- $fullName := printf "%s-%s" (include "codedx.fullname" $) .name }}
  name: {{ include "sanitize" $fullName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "codedx.commonLabels" $ | nindent 4 }}
  annotations:
{{ toYaml $.Values.ingress.annotations | trim | indent 4 }}
  {{- if and $.Values.ingress.assumeNginxIngressController $.Values.codedxTls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  {{- end }}
spec:
  {{- if .tls }}
  tls:
  - hosts:
    - {{ .name | quote }}
    secretName: {{ .tlsSecret | quote }}
  {{- end }}
  rules:
  - host: {{ .name | quote }}
    http:
      paths:
      - path: /codedx
        backend:
          serviceName: {{ include "codedx.fullname" $ | quote }}
          {{- if $.Values.codedxTls.enabled }}
          servicePort: {{ $.Values.codedxTlsTomcatPort }}
          {{- else }}
          servicePort: {{ $.Values.codedxTomcatPort }}
          {{- end }}
---
{{- end -}}
{{- end -}}